# Generated by Django 4.2.17 on 2025-04-13 08:00

import colorfield.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('phone', models.CharField(max_length=20, unique=True, verbose_name='Телефон')),
                ('first_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='Фамилия')),
                ('ext_id', models.CharField(blank=True, max_length=150, null=True, verbose_name='Внешний ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('auth_token', models.UUIDField(blank=True, null=True, unique=True)),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователя',
                'verbose_name_plural': 'Пользователи',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='CategoryContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование категории')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет категории')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категорию',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='CompanyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование компании')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Компанию',
                'verbose_name_plural': 'Компании',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=300, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=300, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=300, null=True, verbose_name='Отчество')),
                ('nickname', models.CharField(blank=True, max_length=300, null=True, verbose_name='Никнейм')),
                ('comment', models.TextField(blank=True, null=True, verbose_name='Комментарий')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contacts/photos/', verbose_name='Фото сотрудника')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.categorycontact', verbose_name='Категория')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.companycontact', verbose_name='Компания')),
            ],
            options={
                'verbose_name': 'Человека',
                'verbose_name_plural': 'Люди',
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование соцсети')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Социальную сеть',
                'verbose_name_plural': 'Социальные сети',
            },
        ),
        migrations.CreateModel(
            name='TypeGuestContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование типа')),
                ('color', colorfield.fields.ColorField(default='#FFFFFF', image_field=None, max_length=25, samples=None, verbose_name='Цвет типа')),
                ('comment', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Тип гостя',
                'verbose_name_plural': 'Типы гостя',
            },
        ),
        migrations.CreateModel(
            name='ModuleInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование cобытия')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Адрес проведения')),
                ('date_start', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время начала')),
                ('date_end', models.DateTimeField(blank=True, null=True, verbose_name='Дата и время окончания')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Отображать')),
                ('checkers', models.ManyToManyField(blank=True, related_name='checker_events', to=settings.AUTH_USER_MODEL, verbose_name='Модераторы')),
                ('managers', models.ManyToManyField(blank=True, related_name='manager_events', to=settings.AUTH_USER_MODEL, verbose_name='Менеджеры')),
                ('producers', models.ManyToManyField(blank=True, related_name='producer_events', to=settings.AUTH_USER_MODEL, verbose_name='Продюсеры')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='InfoContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=255, verbose_name='Имя или айди')),
                ('subscribers', models.IntegerField(blank=True, null=True, verbose_name='Подписчики')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.contact', verbose_name='Человек')),
                ('social_network', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.socialnetwork', verbose_name='Социальная сеть')),
            ],
            options={
                'verbose_name': 'Контакт человека',
                'verbose_name_plural': 'Контакты человека',
            },
        ),
        migrations.AddField(
            model_name='contact',
            name='type_guest',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.typeguestcontact', verbose_name='Тип гостя'),
        ),
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('new', 'Регистрация'), ('checkin', 'Чекин')], db_index=True, default='new', max_length=100, verbose_name='Тип действия')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания записи')),
                ('update_date', models.DateTimeField(auto_now=True, null=True, verbose_name='Дата изменения записи')),
                ('contact', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.contact', verbose_name='Контакт')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='event.moduleinstance', verbose_name='Мероприятие')),
                ('update_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='update_user', to=settings.AUTH_USER_MODEL, verbose_name='Кто обновил')),
            ],
            options={
                'verbose_name': 'Действие',
                'verbose_name_plural': 'Все действия',
            },
        ),
        migrations.CreateModel(
            name='CheckerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Модератора',
                'verbose_name_plural': 'Модераторы',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('event.customuser',),
        ),
        migrations.CreateModel(
            name='ManagerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Менеджера',
                'verbose_name_plural': 'Менеджеры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('event.customuser',),
        ),
        migrations.CreateModel(
            name='ProducerUser',
            fields=[
            ],
            options={
                'verbose_name': 'Продюсера',
                'verbose_name_plural': 'Продюсеры',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('event.customuser',),
        ),
        migrations.AddConstraint(
            model_name='contact',
            constraint=models.UniqueConstraint(fields=('last_name', 'first_name', 'middle_name'), name='unique_contact', violation_error_message='Человек с указанными ФИО уже существует в системе.'),
        ),
        migrations.AddConstraint(
            model_name='action',
            constraint=models.UniqueConstraint(fields=('contact', 'event'), name='unique_reg_contact_to_event', violation_error_message='Человек уже зарегистрирован на данное мероприятие.'),
        ),
    ]
