# Generated by Django 5.1.4 on 2024-12-23 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_categorycontact_company_contact_fio_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['fio'], 'verbose_name': 'Человек', 'verbose_name_plural': 'Люди'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='date_of_birth',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='email',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='sex',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='validated',
        ),
    ]
