# Generated by Django 4.2.17 on 2024-12-23 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_contact_options_remove_contact_create_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/photos/', verbose_name='Фото сотрудника'),
        ),
    ]
