# Generated by Django 4.2.17 on 2025-04-23 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_alter_contact_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='producer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Продюсер'),
        ),
    ]
