# Generated by Django 4.2.17 on 2025-04-23 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_alter_contact_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('announced', 'Заявлен'), ('approved', 'Подтвержден'), ('cancelled', 'Отменен'), ('new', 'Зарегистрирован'), ('checkin', 'Чекин')], db_index=True, default='announced', max_length=100, verbose_name='Тип действия'),
        ),
    ]
