# Generated by Django 4.2.17 on 2024-12-25 13:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_contact_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='checkin',
            options={'ordering': ['pk'], 'verbose_name': 'Регистрация', 'verbose_name_plural': 'Регистрации на мероприятия'},
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='name',
            field=models.CharField(default=1, max_length=100, verbose_name='Наименование cобытия'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.module', verbose_name='Родительский модуль'),
        ),
    ]
