# Generated by Django 4.2.17 on 2024-12-27 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_checkin_options_moduleinstance_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='module',
            name='event',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='is_notify',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='module',
        ),
        migrations.RemoveField(
            model_name='moduleinstance',
            name='visible',
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес проведения'),
        ),
        migrations.DeleteModel(
            name='Event',
        ),
        migrations.DeleteModel(
            name='EventType',
        ),
        migrations.DeleteModel(
            name='Module',
        ),
    ]
