# Generated by Django 4.2.17 on 2025-04-23 15:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0005_alter_action_action_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='action',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий'),
        ),
        migrations.CreateModel(
            name='ActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Предыдущий статус')),
                ('new_status', models.CharField(blank=True, max_length=100, null=True, verbose_name='Новый статус')),
                ('create_date', models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания записи')),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='event.action', verbose_name='Действие')),
                ('create_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Запись аудита',
                'verbose_name_plural': 'Аудит действий',
            },
        ),
    ]
