# Generated by Django 4.2.17 on 2024-12-27 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_remove_module_event_remove_moduleinstance_is_notify_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('new', 'Регистрация'), ('checkin', 'Чекин'), ('cancel', 'Отмена')], default='new', max_length=100, verbose_name='Тип действия'),
        ),
        migrations.DeleteModel(
            name='ActionType',
        ),
    ]
