# Generated by Django 4.2.17 on 2025-04-23 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_action_comment_actionlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionlog',
            name='new_status',
            field=models.CharField(choices=[('announced', 'Заявлен'), ('approved', 'Подтвержден'), ('cancelled', 'Отменен'), ('new', 'Зарегистрирован'), ('checkin', 'Чекин')], default='new', max_length=100, verbose_name='Новый статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='old_status',
            field=models.CharField(choices=[('announced', 'Заявлен'), ('approved', 'Подтвержден'), ('cancelled', 'Отменен'), ('new', 'Зарегистрирован'), ('checkin', 'Чекин')], default='checkin', max_length=100, verbose_name='Предыдущий статус'),
            preserve_default=False,
        ),
    ]
