# Generated by Django 4.2.17 on 2024-12-27 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0007_alter_action_action_type_delete_actiontype'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='action',
            options={'verbose_name': 'Действие', 'verbose_name_plural': 'Все действия'},
        ),
        migrations.AlterModelOptions(
            name='moduleinstance',
            options={'verbose_name': 'Мероприятие', 'verbose_name_plural': 'Мероприятия'},
        ),
    ]
