# Generated by Django 4.2.17 on 2024-12-28 09:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0008_alter_action_options_alter_moduleinstance_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='action',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.contact', verbose_name='Контакт'),
        ),
        migrations.AlterField(
            model_name='action',
            name='module_instance',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='event.moduleinstance', verbose_name='Мероприятие'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.categorycontact', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='event.company', verbose_name='Компания'),
        ),
    ]
