# Generated by Django 4.2.17 on 2025-01-15 21:05

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('event', '0009_alter_action_contact_alter_action_module_instance_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moduleinstance',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_events', to=settings.AUTH_USER_MODEL, verbose_name='Администраторы'),
        ),
        migrations.AddField(
            model_name='moduleinstance',
            name='checkers',
            field=models.ManyToManyField(blank=True, related_name='checker_events', to=settings.AUTH_USER_MODEL, verbose_name='Проверяющие'),
        ),
    ]
