# Generated by Django 4.2.17 on 2025-01-15 21:10

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('event', '0010_moduleinstance_admins_moduleinstance_checkers'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='admins',
            field=models.ManyToManyField(blank=True, related_name='admin_events', to='event.customuser', verbose_name='Администраторы'),
        ),
        migrations.AlterField(
            model_name='moduleinstance',
            name='checkers',
            field=models.ManyToManyField(blank=True, related_name='checker_events', to='event.customuser', verbose_name='Проверяющие'),
        ),
    ]
