# Generated by Django 4.2.17 on 2026-08-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0010_contactduplicateconflict'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': 'Сообщество', 'verbose_name_plural': 'Сообщества'},
        ),
        migrations.AlterModelOptions(
            name='infocontact',
            options={'verbose_name': 'Контакт', 'verbose_name_plural': 'Контакты'},
        ),
        migrations.AlterField(
            model_name='action',
            name='action_type',
            field=models.CharField(choices=[('announced', 'Заявлен'), ('invited', 'Приглашён'), ('registered', 'Зарегистрирован'), ('cancelled', 'Отменён'), ('visited', 'Зачекинен')], db_index=True, default='announced', max_length=100, verbose_name='Тип действия'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='new_status',
            field=models.CharField(choices=[('announced', 'Заявлен'), ('invited', 'Приглашён'), ('registered', 'Зарегистрирован'), ('cancelled', 'Отменён'), ('visited', 'Зачекинен')], max_length=100, verbose_name='Новый статус'),
        ),
        migrations.AlterField(
            model_name='actionlog',
            name='old_status',
            field=models.CharField(choices=[('announced', 'Заявлен'), ('invited', 'Приглашён'), ('registered', 'Зарегистрирован'), ('cancelled', 'Отменён'), ('visited', 'Зачекинен')], max_length=100, verbose_name='Предыдущий статус'),
        ),
    ]
