# Generated by Django 4.2.17 on 2025-04-13 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FSMState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('state', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Состояние пользователя в боте',
                'unique_together': {('bot_id', 'chat_id', 'user_id')},
            },
        ),
        migrations.CreateModel(
            name='FSMData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bot_id', models.BigIntegerField()),
                ('chat_id', models.BigIntegerField()),
                ('user_id', models.BigIntegerField()),
                ('data', models.JSONField(default=dict)),
            ],
            options={
                'verbose_name': 'Данные пользователя в боте',
                'unique_together': {('bot_id', 'chat_id', 'user_id')},
            },
        ),
    ]
